chat_id: <int chat id>
bot_token: "<token>"
input_folder: "C:/Users/<username>/Videos/Radeon ReLive"
output_folder: "C:/Users/<username>/Videos/optimized"
ffmpeg_flags:
  - "-y"
  - "-r"
  - "30"
  - "-vf"
  - "scale=1280:720"
  - "-aspect"
  - "16:9"
  - "-b:v"
  - "2048k"
  - "-c:v"
  - "h264_amf" # update to any encoder available hardware ones: (h264_amf, h264_nvenc, h264_qsv)
  - "-preset"
  - "slow"
  - "-maxrate"
  - "2M"
  - "-bufsize"
  - "4M"
  - "-movflags"
  - "+faststart"
