name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build Windows x64 executable
        run: GOOS=windows GOARCH=amd64 go build -o clip.exe

      - name: Prepare release folder
        run: |
          mkdir release
          mv clip.exe release/
          cp config_template.yml release/

      - name: Create zip archive
        run: |
          cd release
          zip -r ../release.zip .

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: release
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
